version: '3.9'

services:
  postgres:
    container_name: pigpay_postgres
    image: bitnami/postgresql:latest
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    volumes:
      - edutech_pg_data:/bitnami/postgresql
    restart: unless-stopped

volumes:
  edutech_pg_data:
